### ISSUE TITLE
connector to write to another topic

### ISSUE THREAD

**Issue by digikata** [infinyon/labs-projects#1]
Write a connector sink to apply a set of smartmodule transforms and write the result to another topic.

See fluvio cdk overview https://www.fluvio.io/connectors/cdk/overview/

**Comment by pravintargaryen** [comment]
Hi @digikata,

Shall I take this issue?

**Comment by digikata** [comment]
Hi @pravintargaryen, I appreciate you volunteering to help! However, this issue has actually been covered by the new SDF capability. https://www.fluvio.io/sdf/

If you are interested in adding or enhancing fluvio connectors, please feel free to look at https://github.com/fluvio-connectors to see what connectors the community is working with.

Or you can also look at [help-wanted](https://github.com/infinyon/fluvio/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) issues on fluvio
